services:
  postgres:
    container_name: subs-db
    image: postgres
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: subs-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      subs-network:
        aliases:
          - subs-db
  deploy:
    container_name: subs-app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      URL: jdbc:postgresql://subs-db:5432/subs-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      subs-network:
        aliases:
          - subs-app
networks:
  subs-network:
      name: subs-network